# Generated by Django 4.1.1 on 2022-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0002_dosen_mahasiswa_tenaga_pendidik_delete_buku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='fakultas',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='fakultas',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='nip',
            new_name='nim',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tenaga_pendidik',
            name='foto',
            field=models.CharField(max_length=500),
        ),
    ]
