# Generated by Django 4.1.1 on 2022-10-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=9)),
                ('nama', models.CharField(max_length=9)),
                ('tanggal_lahir', models.CharField(max_length=9)),
                ('photo', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=9)),
                ('fakultas', models.CharField(max_length=9)),
                ('prodi', models.CharField(max_length=9)),
                ('alamat_rumah', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='kelompok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.kelompok'),
        ),
    ]
