# Generated by Django 4.1.1 on 2022-10-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0003_alter_buku_kelompok_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kelompok_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.kelompok'),
        ),
    ]
