# Generated by Django 4.1.1 on 2022-10-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0004_alter_buku_kelompok_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
