# Generated by Django 4.1.1 on 2022-10-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='fakultas_prodi',
            new_name='prodi',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='fakultas_prodi',
            new_name='prodi',
        ),
    ]
